name: GitHub Actions (Gradle)

on: [push, pull_request]

jobs:
  gradle-build-and-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: temurin

      - uses: gradle/actions/setup-gradle@v4

      - name: Build
        run: ./gradlew jar

      - name: Test
        run: ./gradlew test
